name: Build Windows x86
on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn webbuild

    - uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x86' # optional x64 or x86. Defaults to x64 if not specified
    - run: python -m pip install -r server/win32/requirements.txt
    - run: python -m pip install pyinstaller
    - run: pyinstaller -F server/win32/build.spec --distpath server/win32/dist/windows/
    - run: copy server/packet/win/* server/win32/dist/windows/

    - uses: actions/upload-artifact@v2
      with:
        name: vTablet_windows_x86
        path: server/win32/dist/windows # or path/to/artifact

